project:
  type: website
  output-dir: docs

website:
  title: "EpiStats"
  site-url: https://CarlosEpiStats.github.io/blog/
  description: "A blog about Epidemiology and Biostatistics by Carlos Fernández, MD MPH."
  navbar:
    right: 
      - icon: rss
        href: blog.xml
      - icon: github
        href: https://github.com/CarlosEpiStats
      - text: Resources
        menu:
          - text: R Weekly
            href: https://rweekly.org
          - text: R Bloggers
            href: https://www.r-bloggers.com
      - text: Archivo
        href: archive.qmd
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - about.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



