project:
  type: website
  output-dir: docs

website:
  title: "Blog GráficosMédicos"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - about.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



