{
  "hash": "216fc8c97141ca3ca4df02ae469dc66c",
  "result": {
    "markdown": "---\ntitle: \"Exploring the `count()` Function in R’s tidyverse\"\ndate: \"2024-06-03\"\ncategories: ['R', 'tidyverse', 'regex']\ndescription: \"Tips and Tricks in Data Cleaning and Visualization, Part III.\"\nexecute: \n  message: false\nwarning: false\neditor_options: \n  chunk_output_type: console\nformat: \n  html:\n    code-fold: true\n    code-summary: \"Show the code\"\n---\n\n  \n  R's tidyverse is a collection of packages designed for data science. One of the most useful functions within this suite is `count()`, part of the `dplyr` package. This function is used to count occurrences of unique values within a dataset, which is crucial for data analysis and exploratory data analysis (EDA). In this blog post, we'll delve into how `count()` works, particularly with the `sort = TRUE` option, and we'll use datasets from the `medicaldata` package to illustrate its application.\n\n# Introduction to `count()`\n\nThe `count()` function in `dplyr` is designed to count the number of occurrences of each unique value of one or more variables. It returns a data frame with the counts of these values. Here's a basic syntax of the function:\n  \n  `count(data, vars, wt = NULL, sort = FALSE, name = \"n\")`\n\n-   `data`: The data frame.\n-   `vars`: The variable(s) to count unique values of.\n-   `wt`: Optional. If provided, counts will be weighted by this variable.\n-   `sort`: If `TRUE`, the resulting data frame will be sorted in descending order by the count.\n-   `name`: The name of the count column. Default is \"n\".\n\n# Using `count()` with `sort = TRUE`\n\nSetting `sort = TRUE` orders the output by the count in descending order, which is helpful when you want to quickly see the most frequent values.\n\n## Example with the `medicaldata` package\n\nThe `medicaldata` package contains various datasets from medical research, which are great for demonstration. We'll use the `covid_testing` dataset for our example.\n\nFirst, install and load the required packages:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"tidyverse\")\n# install.packages(\"medicaldata\")\n\nlibrary(tidyverse)\nlibrary(medicaldata)\n```\n:::\n\n\nNext, load the `covid_testing` dataset and take a look at its structure:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"covid_testing\")\nglimpse(covid_testing)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 15,524\nColumns: 17\n$ subject_id      <dbl> 1412, 533, 9134, 8518, 8967, 11048, 663, 2158, 3794, 4…\n$ fake_first_name <chr> \"jhezane\", \"penny\", \"grunt\", \"melisandre\", \"rolley\", \"…\n$ fake_last_name  <chr> \"westerling\", \"targaryen\", \"rivers\", \"swyft\", \"karstar…\n$ gender          <chr> \"female\", \"female\", \"male\", \"female\", \"male\", \"female\"…\n$ pan_day         <dbl> 4, 7, 7, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 1…\n$ test_id         <chr> \"covid\", \"covid\", \"covid\", \"covid\", \"covid\", \"covid\", …\n$ clinic_name     <chr> \"inpatient ward a\", \"clinical lab\", \"clinical lab\", \"c…\n$ result          <chr> \"negative\", \"negative\", \"negative\", \"negative\", \"negat…\n$ demo_group      <chr> \"patient\", \"patient\", \"patient\", \"patient\", \"patient\",…\n$ age             <dbl> 0.0, 0.0, 0.8, 0.8, 0.8, 0.8, 0.8, 0.0, 0.0, 0.9, 0.9,…\n$ drive_thru_ind  <dbl> 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, …\n$ ct_result       <dbl> 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45…\n$ orderset        <dbl> 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, …\n$ payor_group     <chr> \"government\", \"commercial\", NA, NA, \"government\", \"com…\n$ patient_class   <chr> \"inpatient\", \"not applicable\", NA, NA, \"emergency\", \"r…\n$ col_rec_tat     <dbl> 1.4, 2.3, 7.3, 5.8, 1.2, 1.4, 2.6, 0.7, 1.0, 7.1, 2.5,…\n$ rec_ver_tat     <dbl> 5.2, 5.8, 4.7, 5.0, 6.4, 7.0, 4.2, 6.3, 5.6, 7.0, 3.8,…\n```\n:::\n:::\n\n\nThe `covid_testing` dataset contains data from deidentified results of COVID-19 testing at the Children's Hospital of Pennsylvania (CHOP) in 2020. Suppose we want to count the number of participants according to the COVID-19 test result and sort the results by the count in descending order. Here's how we can do that:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid_testing %>%\n  count(result, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 2\n  result       n\n  <chr>    <int>\n1 negative 14358\n2 positive   865\n3 invalid    301\n```\n:::\n:::\n\n\n## Interpreting the Results\n\nThe output is a tibble where the first column is the test `result`, and the second column, named `n`, shows the counts. Because we used `sort = TRUE`, the result with the highest count (`negative`) will appear first (n = 14,358 patients), followed by positive results (n = 865), and invalid results (n = 301).\n\n## Adding Multiple Variables\n\nYou can also count combinations of multiple variables. For example, if we want to count combinations of result and gender:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid_testing %>%\n  count(result, gender, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  result   gender     n\n  <chr>    <chr>  <int>\n1 negative female  7237\n2 negative male    7121\n3 positive female   449\n4 positive male     416\n5 invalid  male     155\n6 invalid  female   146\n```\n:::\n:::\n\n\nThis will give us a data frame with the counts of each result-gender combination, sorted by the count.\n\n# Practical Use Cases\n\nThe `count()` function is particularly useful for:\n\n-   **EDA**: Quickly understanding the distribution of values in your dataset.\n-   **Data Cleaning**: Identifying and handling rare or common categories.\n-   **Reporting**: Summarizing data in a clear and sorted manner for presentations or reports.\n\n# Conclusion\n\nThe `count()` function in R's `tidyverse` is a powerful tool for summarizing data. By using the `sort = TRUE` option, you can quickly identify the most frequent values in your dataset. Whether you're counting single variables or combinations of variables, `count()` simplifies the task and makes your data analysis workflow more efficient.\n\nHappy counting!\n\n# References\n\n-   Higgins P (2021). *medicaldata: Data Package for Medical Datasets*. R package version 0.2.0, <https://CRAN.R-project.org/package=medicaldata>.\n\n-   Wickham H, Averick M, Bryan J, Chang W, McGowan LD, François R, Grolemund G, Hayes A, Henry L, Hester J, Kuhn M, Pedersen TL, Miller E, Bache SM, Müller K, Ooms J, Robinson D, Seidel DP, Spinu V, Takahashi K, Vaughan D, Wilke C, Woo K, Yutani H (2019). \"Welcome to the tidyverse.\" *Journal of Open Source Software*, *4*(43), 1686. doi:10.21105/joss.01686 <https://doi.org/10.21105/joss.01686>.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}